#!/bin/sh -e

output="$1"
triple="$2"
xgcc="$3"

file=$output/build-host/bin/${triple}-muslgcc
echo '#!/bin/sh' > $file
echo "exec $xgcc -isystem $output/rootfs/opt/linux-kernel-headers/include -s \"\$@\"" >> $file
s6-chmod 0755 $file
